---
title: Lauren Alyssa Ames
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    theme_color: ''
permalink: "/:title/"
email: laurenalyssaames@gmail.com
description: Lauren Alyssa Ames is a writer specializing in essays, short stories,
  humor, and human interest.  Her first novel is in the works.
url: https://smittenn.github.io
twitter_username: laurynaymes
instagram_username: laurynaymes
exclude:
- webpack
- node_modules
